#Project Euler question 29
#How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

#Again python makes this question easy with no max num size
def pEQuestion(bound):
    cur = 0
    powList = []
    for a in range(2,bound+1):
        for b in range(2,bound+1):
            cur = a**b
            if cur not in powList:
                powList.append(cur)
    return len(powList)
print(pEQuestion(5))



